{
 "title": "Airflow",
 "time": { "from": "2023-09-24T22:00:00.000Z", "to": "2023-11-30T22:59:59.000Z" },
 "panels": [
  {
   "title": "Last Day Device Type",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select device_type, count(user_id) from raw_data\nwhere date = (select max(date) from raw_data )\n group by device_type"
    }
   ]
  },
  {
   "title": "Last Day Page Type",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select page_type, count(user_id) from raw_data\nwhere date = (select max(date) from raw_data )\n group by page_type"
    }
   ]
  },
  {
   "title": "Device Type in Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT date, device_type, COUNT(device_type) FROM raw_data GROUP BY date, device_type"
    }
   ]
  },
  {
   "title": "Page Type in Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT date, page_type, COUNT(page_type) FROM raw_data GROUP BY date, page_type"
    }
   ]
  }
 ]
}